export const FETCH_CARS_REQUEST = 'FETCH_CARS_REQUEST';
export const FETCH_CARS_SUCCESS = 'FETCH_CARS_SUCCESS';
export const FETCH_CARS_FAILURE = 'FETCH_CARS_FAILURE';

export const CREATE_CAR_REQUEST = 'CREATE_CAR_REQUEST';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const CREATE_CAR_FAILURE = 'CREATE_CAR_FAILURE';

export const CHANGE_TABLE_STATE = 'CHANGE_TABLE_STATE';
export const RESET_TABLE_STATE = 'RESET_TABLE_STATE';
